// Plan data, recipes, and shopping list
// Auto-extracted from monolithic index.html

export const DAYS=[
{hdr:'🗓️ Wt 14.04 — biuro',meals:[
{name:'🥣 Serek wiejski z warzywami',rid:'serek-wiejski-sniadanie',alt:{name:'🥣 Twarożek ze szczypiorkiem',rid:'twarozek-szczypiorek',m:[361,31,38,10]},ing:'serek wiejski 200g · chleb 2kr · pomidor · ogórek · papryka',m:[394,29,45,10]},
{name:'🥞 Pieczona owsianka z jogurtem greckim',rid:'pieczona-owsianka',tag:'🍳 2d',tagClass:'cook',ing:'płatki 120g · mleko 300ml · 2 jajka · banan · masło orzechowe 30g · jogurt grecki 150g · maliny',m:[593,32,69,23]},
{name:'🍲 Makaron z soczewicy z cukinią i mozzarellą',rid:'makaron-soczewica-cukinia',tag:'🍳 2d',tagClass:'cook',ing:'makaron soczewicowy 350g · cukinia 2szt · mozzarella 250g · suszone pomidory 100g · czosnek · oliwa',m:[568,36,49,22]},
{name:'🥗 Sałatka jaglana z ciecierzycą i jajkiem',rid:'salatka-jaglana-ciecierzyca',tag:'🍳',tagClass:'cook',ing:'kasza jaglana 100g · ciecierzyca 200g · 2 jajka · pomidorki · papryka · sałata · oliwa',m:[448,20,55,13]},
{name:'🥜 Jabłko',rid:'owoc',ing:'jabłko 1 szt',m:[90,1,22,0]}
]},
{hdr:'🗓️ Śr 15.04 — biuro',meals:[
{name:'🥣 Serek wiejski z warzywami',rid:'serek-wiejski-sniadanie',alt:{name:'🥣 Twarożek ze szczypiorkiem',rid:'twarozek-szczypiorek',m:[361,31,38,10]},ing:'serek wiejski 200g · chleb 2kr · pomidor · ogórek · papryka',m:[394,29,45,10]},
{name:'🥞 Pieczona owsianka z jogurtem greckim',rid:'pieczona-owsianka',tag:'🔄 2/2',tagClass:'left',ing:'resztki z wtorku',m:[593,32,69,23]},
{name:'🍲 Makaron z soczewicy z cukinią i mozzarellą',rid:'makaron-soczewica-cukinia',tag:'🔄 2/2',tagClass:'left',ing:'resztki z wtorku',m:[568,36,49,22]},
{name:'🥗 Kanapki z jajkiem na twardo',rid:'kanapki-jajko',ing:'2 jajka na twardo · chleb 2kr · masło 10g · pomidor · ogórek',m:[430,20,32,22]},
{name:'🥜 Jabłko',rid:'owoc',ing:'jabłko 1 szt',m:[90,1,22,0]}
]},
{hdr:'🗓️ Czw 16.04 — biuro',meals:[
{name:'🥣 Serek wiejski z warzywami',rid:'serek-wiejski-sniadanie',alt:{name:'🥣 Twarożek ze szczypiorkiem',rid:'twarozek-szczypiorek',m:[361,31,38,10]},ing:'serek wiejski 200g · chleb 2kr · pomidor · ogórek · papryka',m:[394,29,45,10]},
{name:'🥞 Budyń jaglany z białkiem i owocami',rid:'budyn-jaglany',tag:'🍳 2d',tagClass:'cook',ing:'kasza jaglana (resztki!) · mleko 400ml · banan · białko 40g · maliny 100g',m:[470,31,75,6]},
{name:'🍲 Spaghetti bolońskie (drobiowe)',rid:'spaghetti-bolognese',tag:'🍳 2d',tagClass:'cook',ing:'mielone drobiowe 500g · makaron 500g · pomidory 800g · marchew · cebula · czosnek',m:[510,35,62,12]},
{name:'🥗 Jajka po turecku',rid:'jajka-po-turecku',ing:'2 jajka · jogurt 150g · masło 15g · papryka wędzona · chleb 1kr',m:[451,24,24,30]},
{name:'🥜 Jogurt grecki z bananem',rid:'jogurt-orzechy',ing:'jogurt grecki 200g · banan 0.5szt',m:[200,21,30,2]}
]},
{hdr:'🗓️ Pt 17.04',meals:[
{name:'🥣 Shakshuka ze szpinakiem i fetą',rid:'shakshuka',tag:'🍳 2d',tagClass:'cook',ing:'4 jajka · szpinak 50g · feta 100g · pomidory puszka 400g · cebula · czosnek · oliwa',m:[432,26,14,30]},
{name:'🥞 Budyń jaglany z białkiem i owocami',rid:'budyn-jaglany',tag:'🔄 2/2',tagClass:'left',ing:'resztki z czwartku',m:[470,31,75,6]},
{name:'🍲 Spaghetti bolońskie (drobiowe)',rid:'spaghetti-bolognese',tag:'🔄 2/2',tagClass:'left',ing:'resztki z czwartku',m:[510,35,62,12]},
{name:'🥗 Sałatka ze śliwkami i parmezanem',rid:'salatka-sliwki-parmezan',ing:'rukola 100g · śliwki suszone 80g · parmezan 60g · orzechy włoskie 20g · oliwa',m:[370,15,30,23]},
{name:'🥜 Serek wiejski z warzywami',rid:'serek-wiejski-przekaska',alt:{name:'🥜 Jogurt grecki z orzechami',rid:'jogurt-orzechy',m:[200,12,16,11]},ing:'serek wiejski 100g · pomidor · ogórek',m:[130,13,11,4]}
]},
{hdr:'🗓️ Sob 18.04',meals:[
{name:'🥣 Shakshuka ze szpinakiem i fetą',rid:'shakshuka',tag:'🔄 2/2',tagClass:'left',ing:'resztki z piątku',m:[432,26,14,30]},
{name:'🥞 Placuszki bananowe z jogurtem greckim',rid:'placuszki-bananowe',tag:'🍳',tagClass:'cook',ing:'banan · 2 jajka · płatki 30g · olej · jogurt grecki 150g · maliny 50g',m:[649,35,61,32]},
{name:'🍲 Ryba smażona z frytkami i surówką',rid:'ryba-frytki',tag:'🍳',tagClass:'cook',ing:'filet rybny 300g · frytki mrożone 500g · ogórek',m:[563,32,50,23]},
{name:'🥗 Herbata zielona',ing:'herbata 1 filiżanka',m:[2,0,0,0]},
{name:'🥜 Jabłko',rid:'owoc',ing:'jabłko 1 szt',m:[90,1,22,0]}
]}
];

export const SHOP=[
["🥖 Pieczywo",["chleb żytni — 2 × 500g"]],
["🍌 Owoce / warzywa",["banany — 1 × 1kg (~5szt)","pomidory — 1 × 500g","pomidory koktajlowe — 1 × 250g","ogórki — 5 szt","papryka — 1 × 3 szt","cebula — 3 szt (z 1kg)","marchew — 2 szt (z 1kg)","cukinia — 2 szt","szpinak — 1 × 100g","rukola — 1 × 100g","sałata mix — 1 × 150g","czosnek — 1 × 3 szt"]],
["🥫 Puszki",["pomidory krojone — 4 × 400g","ciecierzyca — 1 × 400g"]],
["🌾 Suche / kasze",["makaron z soczewicy — 1 opak ~350g","makaron — 1 × 500g","kasza jaglana — 1 × 400g","płatki owsiane — 1 × 500g","masło orzechowe — 1 × 350g","suszone pomidory w oleju — 1 słoik 280g","śliwki suszone — 1 × 200g"]],
["🥚 Jajka / mleko / mąka",["jajka — 3 × 10 szt","mleko — 2 × 1L","mąka — 1 × 1kg"]],
["🥩 Mięso",["mięso mielone drobiowe — 1 × 500g"]],
["🧀 Nabiał",["serek wiejski — 4 × 200g","jogurt grecki — 3 × 400g","jogurt naturalny — 1 × 400g","masło — 1 × 200g","feta — 1 × 200g","mozzarella — 2 × 125g","parmezan — 1 × 200g"]],
["🐟 Ryby",["filet rybny — 1 × 400g"]],
["❄️ Mrożonki",["maliny mrożone — 2 × 300g","frytki mrożone — 1 × 1kg"]],
["📦 Inne",["białko w proszku — ~80g","orzechy włoskie — 1 × 100g","oliwa — 1 × 500ml","olej rzepakowy — 1 × 1L"]]
];

export const RECIPES=[
['jajka-na-masle','Jajka na maśle','b',440,26,16,31,[{item:'jajka',amount:'3 szt'},{item:'masło',amount_g:'15'},{item:'chleb żytni',amount:'1 kromka'}],'',['polish','quick'],10],
['shakshuka','Shakshuka ze szpinakiem i fetą','b',432,26,14,30,[{item:'jajka',amount:'4 szt'},{item:'szpinak',amount_g:'50'},{item:'feta',amount_g:'100'},{item:'pomidory krojone puszka',amount_g:'400'},{item:'cebula',amount:'0.5 szt'},{item:'oliwa',amount_g:'15'}],'',['mediterranean','fertility'],25],
['pasta-jajeczna-tunczyk','Pasta jajeczna z tuńczykiem','b',522,43,30,26,[{item:'jajka',amount:'2 szt'},{item:'tuńczyk puszka',amount_g:'85'},{item:'majonez',amount_g:'15'},{item:'chleb żytni',amount:'2 kromki'}],'',['quick','high_protein'],15],
['twarozek-szczypiorek','Twarożek z jogurtem i szczypiorkiem','b',361,31,38,10,[{item:'twaróg',amount_g:'250'},{item:'jogurt naturalny',amount_g:'200'},{item:'chleb żytni',amount:'4 kromki'}],'',['polish','vegetarian'],10],
['kanapki-camembert-parma','Kanapki z camembertem i parmeńską','b',472,27,48,20,[{item:'camembert',amount_g:'60'},{item:'szynka parmeńska',amount_g:'30'},{item:'chleb żytni',amount:'2 kromki'}],'',['mediterranean'],10],
['jajka-sadzone-boczek','Jajka sadzone z boczkiem','b',602,30,16,47,[{item:'jajka',amount:'3 szt'},{item:'boczek wędzony',amount_g:'50'},{item:'chleb żytni',amount:'1 kromka'}],'',['polish','keto_friendly'],15],
['jajka-po-turecku','Jajka po turecku','b',451,24,24,30,[{item:'jajka',amount:'2 szt'},{item:'jogurt naturalny',amount_g:'150'},{item:'masło',amount_g:'15'},{item:'chleb żytni',amount:'1 kromka'}],'',['mediterranean'],15],
['kanapki-pasztet','Kanapki z pasztetem','b',366,13,38,19,[{item:'pasztet',amount_g:'60'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory',amount_g:'75'},{item:'ogórek',amount_g:'75'}],'',['polish','quick'],5],
['kanapki-hummus','Kanapki z hummusem','b',286,11,45,8,[{item:'hummus',amount_g:'60'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory',amount_g:'75'},{item:'papryka',amount_g:'75'}],'',['mediterranean','vegetarian'],5],
['kanapki-ser-wedlina','Kanapki z serem i wędliną','b',379,23,36,16,[{item:'ser żółty',amount_g:'40'},{item:'wędlina',amount_g:'40'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory',amount_g:'75'}],'',['polish','quick'],5],
['serek-wiejski-sniadanie','Serek wiejski z warzywami','b',394,29,45,10,[{item:'serek wiejski',amount_g:'200'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory',amount_g:'75'},{item:'ogórek',amount_g:'75'},{item:'papryka',amount_g:'75'}],'Śniadanie biurowe ~3x/tyg',['polish','quick','high_protein'],5],
['pieczona-owsianka','Pieczona owsianka z jogurtem','sb',593,32,69,23,[{item:'płatki owsiane',amount_g:'120'},{item:'mleko',amount_g:'300'},{item:'jajka',amount:'2 szt'},{item:'banan',amount:'1 szt'},{item:'masło orzechowe',amount_g:'30'},{item:'jogurt grecki',amount_g:'150'},{item:'maliny',amount_g:'30'}],'',['vegetarian','meal_prep'],35],
['budyn-jaglany','Budyń jaglany z białkiem','sb',470,31,75,6,[{item:'kasza jaglana',amount_g:'120'},{item:'mleko',amount_g:'400'},{item:'banan',amount:'1 szt'},{item:'białko w proszku',amount_g:'40'},{item:'maliny',amount_g:'100'}],'Z resztek kaszy jaglanej',['vegetarian','high_protein'],25],
['placuszki-bananowe','Placuszki bananowe z jogurtem','sb',649,35,61,32,[{item:'banan',amount:'1 szt'},{item:'jajka',amount:'2 szt'},{item:'płatki owsiane',amount_g:'30'},{item:'olej rzepakowy',amount_g:'10'},{item:'jogurt grecki',amount_g:'150'},{item:'maliny',amount_g:'50'}],'',['vegetarian','quick'],20],
['nalesniki','Naleśniki z twarożkiem','sb',619,46,60,22,[{item:'mąka',amount_g:'60'},{item:'mleko',amount_g:'150'},{item:'jajka',amount:'1 szt'},{item:'twaróg',amount_g:'150'},{item:'masło',amount_g:'10'}],'',['polish','vegetarian'],30],
['shake-bialkowy','Shake białkowy z owocami','sb',273,32,30,4,[{item:'białko w proszku',amount_g:'30'},{item:'mleko',amount_g:'200'},{item:'banan',amount:'0.5 szt'},{item:'maliny',amount_g:'30'}],'',['quick','high_protein'],5],
['watrobka-ziemniaki','Wątróbka z ziemniakami','d',745,52,78,25,[{item:'wątróbka drobiowa',amount_g:'500'},{item:'ziemniaki',amount_g:'800'},{item:'cebula',amount:'2 szt'},{item:'masło',amount_g:'30'}],'',['polish','fertility'],40],
['curry','Curry z kurczakiem i batatami','d',642,46,69,19,[{item:'pierś kurczaka',amount_g:'750'},{item:'mleko kokosowe',amount_g:'400'},{item:'pasta curry',amount_g:'35'},{item:'ryż',amount_g:'360'},{item:'papryka',amount:'1 szt'}],'',['asian','slow_cook','fertility'],50],
['tofu-bulgogi','Tofu bulgogi','d',327,13,48,10,[{item:'tofu',amount_g:'400'},{item:'sos sojowy',amount_g:'30'},{item:'ryż',amount_g:'200'},{item:'cebula',amount:'1 szt'}],'',['asian','vegetarian'],35],
['spaghetti-bolognese','Spaghetti bolońskie','d',544,26,68,18,[{item:'mięso mielone wieprzowo wołowe',amount_g:'500'},{item:'makaron',amount_g:'500'},{item:'pomidory krojone puszka',amount_g:'700'},{item:'cebula',amount:'1 szt'},{item:'marchew',amount:'1 szt'}],'',['mediterranean','comfort'],45],
['ryz-kurczak-warzywa','Ryż z kurczakiem i warzywami','d',484,46,58,5,[{item:'pierś kurczaka',amount_g:'500'},{item:'ryż',amount_g:'250'},{item:'sos sojowy',amount_g:'20'}],'',['asian','quick','high_protein'],30],
['gulasz-wolowy','Gulasz wołowy z kaszą','d',681,52,51,33,[{item:'wołowina gulaszowa',amount_g:'1000'},{item:'kasza gryczana',amount_g:'360'},{item:'marchew',amount:'2 szt'},{item:'cebula',amount:'2 szt'}],'',['polish','slow_cook','fertility'],120],
['ryba-frytki','Ryba z frytkami','d',563,32,50,23,[{item:'filet rybny',amount_g:'300'},{item:'frytki mrożone',amount_g:'500'},{item:'ogórek',amount_g:'100'}],'Frytki mrożone z piekarnika, nie domowe',['polish','comfort','quick'],25],
['pieczone-udka','Pieczone udka z dodatkami','d',703,68,30,33,[{item:'udo kurczaka',amount_g:'1000'},{item:'ziemniaki',amount_g:'600'},{item:'marchew',amount:'2 szt'},{item:'oliwa',amount_g:'20'}],'',['polish','high_protein'],60],
['mielone-por','Mielone z porem i marchewką','d',467,30,11,33,[{item:'mięso mielone wieprzowo wołowe',amount_g:'600'},{item:'marchew',amount:'2 szt'},{item:'jajka',amount:'2 szt'}],'',['polish','comfort'],50],
['kotlety-udka','Kotlety z udek z ziemniakami','d',604,59,35,24,[{item:'udo kurczaka',amount_g:'800'},{item:'bułka tarta',amount_g:'50'},{item:'jajka',amount:'1 szt'},{item:'ziemniaki',amount_g:'600'}],'',['polish','high_protein'],50],
['kaszotto-buraczane','Kaszotto buraczane z kurczakiem','d',411,38,45,8,[{item:'kasza jęczmienna',amount_g:'200'},{item:'pierś kurczaka',amount_g:'400'},{item:'buraki gotowane',amount_g:'250'},{item:'cebula',amount:'1 szt'},{item:'oliwa',amount_g:'15'}],'',['polish','fertility'],45],
['quesadilla-kurczak','Quesadilla z kurczakiem','d',464,44,34,16,[{item:'pierś kurczaka',amount_g:'400'},{item:'tortilla',amount:'4 szt'},{item:'cukinia',amount:'1 szt'},{item:'ser żółty',amount_g:'100'},{item:'jogurt naturalny',amount_g:'100'}],'',['mexican','quick'],25],
['tortilla-kurczak','Tortilla z kurczakiem','d',400,38,39,10,[{item:'pierś kurczaka',amount_g:'400'},{item:'tortilla',amount:'4 szt'},{item:'papryka',amount:'2 szt'},{item:'jogurt naturalny',amount_g:'150'}],'',['mexican','mediterranean'],30],
['makaron-ryzowy-tajski','Makaron ryżowy po tajsku','d',555,36,82,7,[{item:'makaron ryżowy',amount_g:'350'},{item:'pierś kurczaka',amount_g:'400'},{item:'sos sojowy',amount_g:'30'}],'',['asian','quick'],25],
['makaron-soczewica-cukinia','Makaron z soczewicy z cukinią','d',568,36,49,22,[{item:'makaron z soczewicy',amount_g:'350'},{item:'cukinia',amount:'2 szt'},{item:'mozzarella',amount_g:'250'},{item:'suszone pomidory w oleju',amount_g:'100'},{item:'oliwa',amount_g:'20'}],'Suszone pomidory w oleju zamiast puszki',['mediterranean','vegetarian'],25],
['salatka-jaglana-halloumi','Sałatka jaglana z halloumi','s',733,37,63,38,[{item:'kasza jaglana',amount_g:'120'},{item:'halloumi',amount_g:'225'},{item:'papryka',amount:'1 szt'},{item:'kukurydza puszka',amount_g:'100'},{item:'oliwa',amount_g:'15'}],'',['mediterranean','vegetarian'],30],
['placki-ziemniaczane','Placki ziemniaczane','s',439,11,58,18,[{item:'ziemniaki',amount_g:'500'},{item:'cebula',amount:'1 szt'},{item:'jajka',amount:'1 szt'},{item:'mąka',amount_g:'30'},{item:'olej rzepakowy',amount_g:'30'}],'',['polish','vegetarian'],35],
['salatka-ciecierzyca','Sałatka z ciecierzycą','s',246,11,22,13,[{item:'ciecierzyca puszka',amount_g:'200'},{item:'sałata mix',amount_g:'75'},{item:'pomidory koktajlowe',amount_g:'80'},{item:'feta',amount_g:'50'},{item:'oliwa',amount_g:'10'}],'',['mediterranean','vegetarian','fertility'],20],
['salatka-sliwki-parmezan','Sałatka ze śliwkami i parmezanem','s',370,15,30,23,[{item:'rukola',amount_g:'100'},{item:'śliwki suszone',amount_g:'80'},{item:'parmezan',amount_g:'60'},{item:'orzechy włoskie',amount_g:'20'},{item:'oliwa',amount_g:'15'}],'',['mediterranean','vegetarian'],15],
['salatka-gruszka-blue','Sałatka z gruszką i blue','s',396,13,30,26,[{item:'sałata mix',amount_g:'100'},{item:'gruszka',amount:'2 szt'},{item:'ser blue',amount_g:'100'},{item:'orzechy włoskie',amount_g:'20'},{item:'oliwa',amount_g:'10'}],'',['mediterranean','vegetarian'],15],
['pieczony-camembert','Pieczony camembert z miodem','s',451,19,37,26,[{item:'camembert',amount_g:'120'},{item:'miód',amount_g:'15'},{item:'orzechy włoskie',amount_g:'30'},{item:'chleb żytni',amount:'4 kromki'}],'',['comfort','vegetarian'],20],
['serek-losos','Serek śmietankowy z łososiem','s',414,17,31,25,[{item:'serek śmietankowy',amount_g:'60'},{item:'łosoś wędzony',amount_g:'50'},{item:'chleb żytni',amount:'2 kromki'}],'',['quick','fertility'],10],
['pizzerinki-wiejski','Pizzerinki z serka wiejskiego','s',434,26,51,13,[{item:'serek wiejski',amount_g:'200'},{item:'mąka',amount_g:'110'},{item:'ser żółty',amount_g:'50'},{item:'wędlina',amount_g:'30'},{item:'kukurydza puszka',amount_g:'50'}],'',['polish','vegetarian'],25],
['salatka-jaglana-ciecierzyca','Sałatka jaglana z ciecierzycą','s',448,20,55,13,[{item:'kasza jaglana',amount_g:'100'},{item:'ciecierzyca puszka',amount_g:'200'},{item:'jajka',amount:'2 szt'},{item:'pomidory koktajlowe',amount_g:'80'},{item:'papryka',amount_g:'75'},{item:'sałata mix',amount_g:'75'},{item:'oliwa',amount_g:'10'}],'Gotuj extra kaszę na budyń',['mediterranean','fertility'],25],
['kanapki-pasztet-s','Kanapki z pasztetem','s',366,13,38,19,[{item:'pasztet',amount_g:'60'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory',amount_g:'75'}],'',['polish','quick'],5],
['kanapki-hummus-s','Kanapki z hummusem','s',286,11,45,8,[{item:'hummus',amount_g:'60'},{item:'chleb żytni',amount:'2 kromki'},{item:'papryka',amount_g:'75'}],'',['mediterranean','vegetarian'],5],
['kanapki-ser-wedlina-s','Kanapki z serem i wędliną','s',379,23,36,16,[{item:'ser żółty',amount_g:'40'},{item:'wędlina',amount_g:'40'},{item:'chleb żytni',amount:'2 kromki'}],'',['polish','quick'],5],
['kanapki-jajko','Kanapki z jajkiem na twardo','s',430,20,32,22,[{item:'jajka',amount:'2 szt'},{item:'chleb żytni',amount:'2 kromki'},{item:'masło',amount_g:'10'},{item:'pomidory',amount_g:'75'},{item:'ogórek',amount_g:'75'}],'',['polish','quick'],10],
['pasta-tunczyk-prosty','Pasta z tuńczyka na kanapkach','s',380,28,30,16,[{item:'tuńczyk puszka',amount_g:'170'},{item:'jogurt naturalny',amount_g:'30'},{item:'ogórek',amount_g:'50'},{item:'chleb żytni',amount:'2 kromki'}],'Tuńczyk + jogurt zamiast majonezu',['quick','high_protein'],10],
['pasta-losos','Pasta z łososia wędzonego','s',420,20,30,24,[{item:'łosoś wędzony',amount_g:'50'},{item:'serek śmietankowy',amount_g:'60'},{item:'ogórek',amount_g:'50'},{item:'chleb żytni',amount:'2 kromki'}],'',['quick','fertility'],10],
['kanapki-awokado-jajko','Kanapki z awokado i jajkiem','b',450,18,35,28,[{item:'jajka',amount:'2 szt'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory koktajlowe',amount_g:'50'}],'+ pół awokado',['quick','fertility'],10],
['overnight-oats','Overnight oats z jogurtem','sb',420,22,58,12,[{item:'płatki owsiane',amount_g:'60'},{item:'jogurt grecki',amount_g:'150'},{item:'mleko',amount_g:'100'},{item:'banan',amount:'0.5 szt'},{item:'maliny',amount_g:'30'}],'Przygotować wieczorem, rano gotowe',['quick','vegetarian','meal_prep'],5],
['twarozek-rzodkiewka','Twarożek z rzodkiewką i ogórkiem','b',340,28,36,8,[{item:'twaróg',amount_g:'200'},{item:'jogurt naturalny',amount_g:'100'},{item:'ogórek',amount_g:'50'},{item:'chleb żytni',amount:'2 kromki'}],'Wersja wiosenna',['polish','quick','vegetarian'],10],
['kanapki-szynka-warzywa','Kanapki z szynką drobiową i warzywami','b',332,22,37,11,[{item:'wędlina',amount_g:'60'},{item:'masło',amount_g:'10'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory',amount_g:'75'},{item:'ogórek',amount_g:'75'}],'Chuda szynka z piersi kurczaka/indyka',['polish','quick'],5],
['kanapki-indyk-hummus','Kanapki z indykiem i hummusem','b',306,21,40,7,[{item:'wędlina',amount_g:'50'},{item:'hummus',amount_g:'40'},{item:'chleb żytni',amount:'2 kromki'},{item:'papryka',amount_g:'50'},{item:'pomidory',amount_g:'50'}],'Indyk + hummus zamiast masła',['quick','mediterranean'],5],
['kanapki-feta-rukola','Kanapki z fetą, pomidorkami i rukolą','b',350,14,31,18,[{item:'feta',amount_g:'50'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory koktajlowe',amount_g:'50'},{item:'rukola',amount_g:'20'},{item:'oliwa',amount_g:'5'}],'',['mediterranean','vegetarian','quick'],5],
['kanapki-wiejski-wedlina','Kanapki z serkiem wiejskim i wędliną','b',329,27,34,7,[{item:'serek wiejski',amount_g:'100'},{item:'wędlina',amount_g:'40'},{item:'chleb żytni',amount:'2 kromki'},{item:'pomidory',amount_g:'75'},{item:'ogórek',amount_g:'75'}],'Serek + chuda wędlina = dużo białka',['polish','quick','high_protein'],5],
['shake-przekaska','Shake białkowy','p',273,32,30,4,[{item:'białko w proszku',amount_g:'30'},{item:'mleko',amount_g:'200'}],'',['quick','high_protein'],5],
['jogurt-orzechy','Jogurt grecki z orzechami','p',200,12,16,11,[{item:'jogurt grecki',amount_g:'150'},{item:'orzechy włoskie',amount_g:'15'},{item:'miód',amount_g:'5'}],'',['quick'],5],
['owoc','Jabłko / banan','p',90,1,22,0,[],'',['quick'],1],
['serek-wiejski-przekaska','Serek wiejski z warzywami','p',180,15,10,8,[{item:'serek wiejski',amount_g:'100'},{item:'pomidory',amount_g:'50'}],'',['quick'],5],
['orzeszki-mix','Mix orzechów 40g','p',240,8,6,20,[{item:'orzechy włoskie',amount_g:'40'}],'',['quick'],1]
];

export const RECIPES_INSP=[
['nfz_classic-1','Kakaowa owsianka z żurawiną i jabłkiem','b',449,17,71,13,'nfz'],
['nfz_classic-2','Kurczak duszony w marchewce i pomidorach','d',512,11,26,15,'nfz'],
['nfz_classic-3','Budyń truskawkowo-jaglany','sb',153,6,28,3,'nfz'],
['nfz_classic-4','Omlet z indykiem i warzywami + grzanka','s',390,8,52,17,'nfz'],
['nfz_classic-7','Dorsz z kiszoną kapustą i ziemniakami','d',528,33,71,16,'nfz'],
['nfz_classic-8','Gryczanka z kiwi i prażonym słonecznikiem','b',453,18,76,12,'nfz'],
['nfz_classic-11','Placki cukiniowe','s',333,18,26,22,'nfz'],
['nfz_dash-12','Omlet po grecku','b',624,40,24,41,'nfz'],
['nfz_dash-13','Makaron penne z dynią, brokułem i kurczakiem','d',468,31,56,15,'nfz'],
['nfz_dash-15','Kokosowa jaglanka z borówkami i daktylami','s',402,8,56,18,'nfz'],
['nfz_dash-17','Ryż z dorszem i szpinakiem','d',604,28,68,23,'nfz'],
['nfz_dash-19','Wegańskie wrapy z kalafiorem i hummusem','s',335,15,39,13,'nfz'],
['nfz_dash-21','Kotlety z soczewicy i kaszy jaglanej','d',521,22,81,14,'nfz'],
['nfz_dash-23','Grzanki z awokado','s',351,6,58,12,'nfz'],
['nfz_weight-26','Pieczony pstrąg z czosnkiem i natką pietruszki','d',705,43,54,37,'nfz'],
['nfz_weight-27','Pieczywo z piersią indyka i pastą z buraka','s',348,22,55,7,'nfz'],
['nfz_weight-29','Pulpety drobiowe z ziemniakami','d',656,36,97,18,'nfz'],
['nfz_weight-33','Pomidorowa kasza gryczana z brokułem','s',397,16,16,7,'nfz'],
['nfz_immunity-34','Czekoladowa jaglanka z truskawkami i malinami','b',497,10,87,15,'nfz'],
['nfz_immunity-36','Tortilla po meksykańsku z mięsem wieprzowym','d',640,42,71,21,'nfz'],
['nfz_immunity-37','Guacamole z rzodkiewką i papryką na grzankach','s',356,8,52,16,'nfz'],
['nfz_immunity-38','Placuszki gryczane z warzywami','b',508,16,45,29,'nfz'],
['nfz_immunity-39','Sałatka na ciepło z warzyw, fety i cieciorki','s',328,17,36,15,'nfz'],
['nfz_immunity-41','Ryż brązowy po meksykańsku z kurczakiem','d',657,51,93,11,'nfz'],
['nfz_immunity-43','Pomidorowa kasza jaglana z tofu i warzywami','d',649,33,75,24,'nfz'],
['nfz_immunity-45','Krem z ciecierzycy','s',350,15,49,11,'nfz'],
['nfz_sport-46','Gryczanka na mleku z bananem i orzechami','b',557,18,92,15,'nfz'],
['nfz_sport-48','Makaron pełnoziarnisty spaghetti z indykiem','d',645,54,74,13,'nfz'],
['nfz_sport-49','Tatar z łososia wędzonego i awokado z grzankami','s',508,26,55,24,'nfz'],
['nfz_sport-50','Grahamka z szynką parmeńską i mozzarellą','b',551,38,64,18,'nfz'],
['nfz_sport-51','Sałatka ryżowa z kurczakiem i warzywami','s',507,32,60,17,'nfz'],
['nfz_sport-52','Jogurt z owocami i orzechowo-jaglaną posypką','sb',402,22,61,10,'nfz'],
['nfz_sport-53','Ciecierzyca w sosie pomidorowym z kaszą gryczaną','d',664,26,107,17,'nfz'],
['nfz_sport-54','Szakszuka pomidorowa z czerwoną fasolą','b',541,25,57,25,'nfz'],
['nfz_sport-55','Naleśniki pełnoziarniste z twarogiem i owocami','d',654,38,74,24,'nfz'],
['nfz_sport-57','Śledź w jogurcie i cebuli z chlebem','s',508,32,55,19,'nfz'],
['fertility-1','Chleb żytni + Feta + Jajo kurze','b',586,25,29,42,'fertility'],
['fertility-3','Chleb żytni + Papryka + Jajo kurze','b',578,26,64,27,'fertility'],
['fertility-6','Chleb żytni + Awokado + Łosoś wędzony','b',530,32,34,32,'fertility'],
['fertility-7','Kasza gryczana + Oliwa + Ciecierzyca','b',557,22,68,24,'fertility'],
['fertility-9','Szpinak + Pomidory puszka + Chleb żytni','b',586,28,57,29,'fertility'],
['fertility-12','Buraki + Czosnek + Orzechy włoskie','b',630,31,34,43,'fertility'],
['fertility-13','Pieczarki + Oliwa + Jajo kurze','b',523,27,31,34,'fertility'],
['fertility-14','Tuńczyk w oliwie + Oliwa','b',497,41,30,23,'fertility'],
['fertility-20','Chleb żytni + Wątroba indyka + Cebula','b',369,23,31,17,'fertility'],
['fertility-27','Jajo kurze + Buraki + Rukola','b',332,19,20,20,'fertility'],
['fertility-29','Indyk mielony + Batat + Jajo kurze','d',642,38,93,16,'fertility'],
['fertility-30','Łopatka wołowa + Quinoa','d',603,30,56,30,'fertility'],
['fertility-32','Kurczak pierś + Oliwa + Warzywa na patelnię','d',503,31,51,17,'fertility'],
['fertility-33','Wątroba indyka + Ziemniaki + Kapusta kiszona','d',637,36,60,30,'fertility'],
['fertility-35','Łosoś dziki + Ziemniaki + Marchew','d',578,36,44,31,'fertility'],
['fertility-36','Dorsz + Oliwa + Brokuł','d',553,36,54,25,'fertility'],
['fertility-37','Kasza jaglana + Buraki + Feta','d',568,21,67,26,'fertility'],
['fertility-38','Wołowina mielona + Makaron orkiszowy + Pomidory','d',569,31,60,25,'fertility'],
['fertility-39','Papryka + Cukinia + Indyk filet','d',689,42,68,29,'fertility'],
['fertility-44','Tuńczyk + Makaron orkiszowy','s',453,30,44,20,'fertility'],
['fertility-45','Kurczak pierś + Kasza gryczana + Oliwa','s',507,28,46,26,'fertility'],
['fertility-46','Krewetki + Ryż basmati + Pomidorki','s',455,28,50,16,'fertility'],
['fertility-47','Kasza jaglana + Łosoś wędzony + Pomidor','s',424,29,48,14,'fertility'],
['fertility-48','Kurczak udko + Rosół + Dynia','s',426,43,41,12,'fertility'],
['fertility-51','Makaron z czerwonej soczewicy + Tofu + Rukola','s',459,28,37,23,'fertility'],
['fertility-53','Quinoa + Rosół + Halloumi','s',578,34,43,32,'fertility'],
['fertility-56','Soczewica czerwona + Batat + Papryka','s',424,29,48,14,'fertility'],
['fodmap-1','Szakszuka dyniowa z fetą','b',415,18,31,21,'fodmap'],
['fodmap-3','Klopsiki z dorsza w sosie pomidorowym','d',416,29,59,6,'fodmap'],
['fodmap-5','Tosty bezglutenowe z tofucznicą','s',371,13,37,16,'fodmap'],
['fodmap-6','Placuszki gryczane z cukinii z łososiem','b',464,28,56,12,'fodmap'],
['fodmap-7','Owsianka jogurtowa z pomarańczą','sb',398,16,49,14,'fodmap'],
['fodmap-10','Sałatka z pieczonej dyni, komosy i fety','s',364,16,34,17,'fodmap'],
['fodmap-11','Pasta jajeczna na bezglutenowym pieczywie','b',403,20,34,17,'fodmap'],
['fodmap-13','Makaron ryżowy z tofu w azjatyckim stylu','d',426,16,56,15,'fodmap'],
['fodmap-15','Bakłażan w sosie pomidorowym','s',367,30,41,8,'fodmap'],
['fodmap-16','Omlet z cukinią i serem feta','b',428,22,24,24,'fodmap'],
['fodmap-18','Grillowana pierś z kurczaka z kaszą i warzywami','d',431,34,46,10,'fodmap'],
['fodmap-20','Fit placki ziemniaczane z koperkiem i fetą','s',332,13,57,5,'fodmap'],
['fodmap-21','Placuszki bananowe','b',467,21,58,16,'fodmap'],
['fodmap-23','Risotto z krewetkami i pomidorami','d',412,26,45,12,'fodmap'],
['fodmap-25','Zupa hiszpańska z kurczakiem i komosą ryżową','s',308,23,25,12,'fodmap'],
['fodmap-26','Naleśniki gryczane','b',402,23,56,8,'fodmap'],
['fodmap-28','Ryż smażony z warzywami i kurczakiem','d',410,20,46,14,'fodmap'],
['fodmap-33','Makaron bezglutenowy z pesto i kurczakiem','d',472,30,50,16,'fodmap'],
['fodmap-35','Twarożek ze szczypiorkiem i ogórkiem','s',308,17,33,7,'fodmap']
];

export const LONG_TERM={2:1,3:1,4:1,8:1,9:1};

export const LONG_TERM_ITEMS={'6_3':1};

